from __future__ import annotations
"""
Synthetic Dataset Generator (50,000+ Records).

⚠️  SIMULATION ASSUMPTION SET — NOT REAL RAZORPAY STATISTICS.
    All records generated by this script have provenance: SYNTHETIC_TRAINING_DATA.

Generates realistic correlated historical recovery attempts:
- Temporary failures (cooldown effects, retry success patterns)
- Insufficient funds (time-delayed payment links, salary date cycles)
- Repeated failures (diminishing returns on retries, payment link shift)
- Invalid payment methods (card expiry requiring method update)
- High-value customer tiers (LTV impact, white-glove escalation benefits)
- Customer fatigue penalty for over-intervention
"""

import argparse
import os
import sys
from pathlib import Path
from typing import List

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd

from simulator.environment import RecoveryEnvironment
from simulator.models import SimActionType, SimFailureType

PROVENANCE = "SYNTHETIC_TRAINING_DATA"


def generate_synthetic_dataset(n_samples: int = 55000, seed: int = 42) -> pd.DataFrame:
    print(f"Generating {n_samples:,} synthetic historical records (seed={seed})...")
    env = RecoveryEnvironment(seed=seed)
    rng = np.random.default_rng(seed)

    records = []
    actions_pool = list(SimActionType)

    # Logging policy: historical behavior mix (60% rule-based / heuristic, 20% fixed retry, 20% exploration)
    for i in range(n_samples):
        if (i + 1) % 10000 == 0:
            print(f"  Processed {i + 1:,} / {n_samples:,} records...")

        state = env.reset(seed=seed + i)
        
        # Pick historical logged action with realistic merchant behavior
        rand_val = rng.random()
        if rand_val < 0.20:
            # Random exploration
            action = actions_pool[rng.integers(0, len(actions_pool))]
        elif rand_val < 0.40:
            # Fixed retry habit
            action = SimActionType.RETRY if state.attempt_count <= 3 else SimActionType.STOP_RECOVERY
        else:
            # Heuristic merchant rule
            if state.failure_type == SimFailureType.TEMPORARY_BANK_FAILURE:
                action = SimActionType.RETRY if state.attempt_count <= 2 else SimActionType.PAYMENT_LINK
            elif state.failure_type == SimFailureType.INSUFFICIENT_FUNDS:
                action = SimActionType.PAYMENT_LINK if rng.random() < 0.65 else SimActionType.SEND_REMINDER
            elif state.failure_type in (SimFailureType.INVALID_PAYMENT_METHOD, SimFailureType.CARD_EXPIRED):
                action = SimActionType.REQUEST_ALTERNATE_METHOD if rng.random() < 0.75 else SimActionType.PAYMENT_LINK
            elif state.amount > 50000.0:
                action = SimActionType.ESCALATE_TO_HUMAN if rng.random() < 0.80 else SimActionType.PAYMENT_LINK
            else:
                action = [SimActionType.WAIT, SimActionType.PAYMENT_LINK, SimActionType.RETRY][rng.integers(0, 3)]

        # Step in simulator
        outcome = env.step(state, action)

        records.append({
            "record_id": f"rec_{i+1:06d}",
            "customer_id": state.customer.id,
            "customer_archetype": state.customer.archetype,
            "customer_ltv": round(state.customer.ltv, 2),
            "customer_failure_rate": round(state.customer.failure_rate, 4),
            "customer_opted_out": state.customer.opted_out,
            "subscription_id": state.subscription.id,
            "subscription_paid_count": state.subscription.paid_count,
            "subscription_remaining_count": state.subscription.remaining_count,
            "amount": round(state.amount, 2),
            "failure_reason": state.failure_type.value,
            "attempt_count": state.attempt_count,
            "hours_since_first_failure": round(state.hours_since_first_failure, 2),
            "interventions_count": state.interventions_count,
            "is_weekend": int(state.is_weekend),
            "action_taken": action.value,
            "recovered": int(outcome.success),
            "recovered_amount": round(outcome.recovered_amount, 2),
            "recovery_time_hours": round(outcome.recovery_time_hours, 2),
            "action_cost": round(outcome.action_cost, 2),
            "friction": round(outcome.friction, 2),
            "reward": round(outcome.reward, 2),
            "provenance": PROVENANCE,
        })

    df = pd.DataFrame(records)
    print(f"Finished generating {len(df):,} records. Recovery rate: {df['recovered'].mean():.2%}, Total simulated revenue recovered: ₹{df['recovered_amount'].sum():,.2f}")
    return df


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate synthetic recovery dataset.")
    parser.add_argument("--samples", type=int, default=55000, help="Number of records to generate")
    parser.add_argument("--output", type=str, default="data/synthetic/historical_records.parquet")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    df = generate_synthetic_dataset(n_samples=args.samples, seed=args.seed)
    df.to_parquet(args.output, index=False)
    csv_path = args.output.replace(".parquet", ".csv")
    df.head(1000).to_csv(csv_path, index=False)
    print(f"Saved full parquet to {args.output} and sample CSV to {csv_path}")
